import type { Evidence } from "./types";

/**
 * Master evidence library distilled from content/asset-inventory.md.
 * Company configs reference these by id - add new entries here once,
 * reuse across every pitch.
 */
export const EVIDENCE: Record<string, Evidence> = {
  "beans": {
    id: "beans",
    device: "laptop",
    title: "Beans",
    period: "Jul 2024 – Jun 2025",
    what: "Pump.fun-style Solana token launcher rendered as a retro Windows-95 desktop: live launches as draggable windows, chat, and physics objects - backed by a custom Anchor program.",
    stack: ["Next.js", "matter-js", "Rust / Anchor", "Jupiter", "Raydium"],
    proofPoints: [
      "Custom bonding-curve math and homegrown Anchor client layer",
      "On-chain program: launches, betting, staking, NFT claims - with bankrun simulation tests",
      "Multi-DEX routing across Jupiter, Raydium and pump.fun",
    ],
    media: { kind: "image", src: "/projects/beans.png", alt: "Beans desktop UI" },
  },
  "keom": {
    id: "keom",
    device: "laptop",
    title: "Keom / 0VIX",
    period: "2022 – 2024",
    what: "Money-market and margin-trading protocol frontends that grew from $500k to $10M TVL.",
    metric: "TVL $500k \u2192 $10M \u00b7 84 of 91 commits",
    stack: ["React", "TypeScript", "Pyth", "Celer", "Cypress"],
    proofPoints: [
      "keom-dapp: 84 of 91 commits - essentially solo on a live-TVL margin/lending dApp",
      "margin-trading-frontend: primary author (55/61 commits), Algebra AMM, e2e tested, i18n",
      "Oracles, bridges, multi-wallet - real production DeFi surface area",
    ],
    media: { kind: "image", src: "/projects/0vix.png", alt: "0VIX lending UI" },
  },
  "vanta-os": {
    id: "vanta-os",
    device: "laptop",
    title: "Vanta",
    period: "Nov 2025 – present",
    what: "The Vanta ecosystem: the marketing/investor landing with custom WebGL, the Vanta OS product (biomarker dashboards, AI chat coach, wearable integrations), and the Society platform - web store, labs, admin, and the App Store mobile app.",
    link: "https://vanta-os.com/prometheus",
    stack: ["Next.js 16", "React 19", "Express 5", "Drizzle", "LLM pipelines"],
    proofPoints: [
      "LLM daily-plan generation with an eval harness",
      "Wearable-data reconciliation engine - 39 phased rollouts logged",
      "End-to-end ownership: product, backend, data model, micro-interactions",
    ],
    media: { kind: "image", src: "/showcase/society/routine.png", alt: "Vanta OS product UI" },
  },
  "vanta-society": {
    id: "vanta-society",
    device: "laptop",
    title: "Vanta Society Platform",
    period: "Feb – Jun 2026",
    what: "Multi-app monolith: e-commerce store, lab-test booking with biomarker/DEXA/genetics report viewers, admin dashboards and marketing surfaces under one shell.",
    metric: "5 app surfaces \u00b7 one architecture",
    stack: ["Next.js 16", "Framer Motion", "Shopify App Bridge", "Express", "Drizzle", "react-pdf"],
    proofPoints: [
      "Multi-tenant app architecture under a single shell",
      "PDF lab-report rendering and biomarker dashboards",
      "Shopify embedded admin app and referral system",
    ],
  },
  "society-mobile": {
    id: "society-mobile",
    device: "phone",
    title: "Vanta Society",
    period: "Sep 2025 – Apr 2026",
    what: "Shipped consumer mobile app: community, marketplace, workouts and challenges, stories, streaks, Strava integration.",
    metric: "Live on the App Store",
    stack: ["Expo / React Native", "Shopify Skia", "FlashList", "EAS"],
    proofPoints: [
      "Mature atomic design system with Skia custom graphics",
      "Shareable social cards, streak and milestone celebration flows",
      "Full EAS pipeline to the App Store",
    ],
  },
  "mudrex": {
    id: "mudrex",
    device: "phone",
    title: "Mudrex",
    period: "pre-2022",
    what: "Built the mobile app from scratch in React Native - 10M+ downloads, carried the company from pre-seed through Series A.",
    metric: "10M+ downloads",
    stack: ["React Native"],
    proofPoints: [
      "10M+ downloads",
      "Zero-to-one under YC-startup constraints",
    ],
    media: { kind: "image", src: "/projects/mudrex-1.png", alt: "Mudrex mobile app" },
  },
  "tokenfolio": {
    id: "tokenfolio",
    device: "laptop",
    title: "TokenFolio",
    period: "Feb 2023 – Mar 2024",
    what: "Investor and token-sale platform: KYC via Onfido, Auth0, deal allocation and staking.",
    stack: ["React", "Onfido", "Auth0", "ApexCharts"],
    proofPoints: [
      "KYC/compliance flows in a crypto context",
      "Allocation staking and deal mechanics",
    ],
  },
  "caddi-lambda": {
    id: "caddi-lambda",
    device: "extension",
    title: "Caddi",
    period: "2023 – 2024",
    what: "Chrome-extension widget that lets you swap and bridge from any website, and aggregates swaps - it checks the swap you're making and flags a better route if one exists. AWS Lambda microservices behind it.",
    stack: ["AWS Lambda", "Farcaster", "Browser extensions", "Next.js"],
    proofPoints: [
      "Serverless microservice architecture in production",
      "Early builder on emerging surfaces (Farcaster Frames, early 2024)",
    ],
    media: { kind: "image", src: "/projects/caddi.png", alt: "Caddi overlay extension" },
  },
  "queues": {
    id: "queues",
    device: "laptop",
    title: "beans_urls - Queue-Driven Launch Pipeline",
    period: "Jun – Jul 2025",
    what: "Paste-a-link → token-launch Telegram bot with BullMQ/Redis workers, metadata scraping, tests and backup/restore scripts.",
    metric: "Shipped in weeks, ran unattended",
    stack: ["BullMQ", "Redis", "Jest", "Express"],
    proofPoints: [
      "Production hygiene: workers, retries, backups, test coverage",
      "Shipped in weeks, post-pivot",
    ],
  },
  "ai-pipelines": {
    id: "ai-pipelines",
    device: "laptop",
    title: "AI Agent Pipelines (reel-editor, vanta-team-os)",
    period: "2025 – 2026",
    what: "Claude-driven media pipeline (FFmpeg/WhisperX/Remotion with human-in-loop review) and a serverless personal OS: Telegram capture → LLM triage → digest.",
    stack: ["Claude API", "FFmpeg", "WhisperX", "Remotion", "Serverless"],
    proofPoints: [
      "Agentic systems with human-in-loop review dashboards",
      "LLM evals and structured pipelines, not just prompt calls",
    ],
  },
  "oss": {
    id: "oss",
    device: "laptop",
    title: "Open Source - StegCloak, AirShare, Teleport",
    period: "pre-2022",
    what: "StegCloak: 2.5K-star JS steganography library. AirShare: 600-star P2P LAN transfer, 40K downloads. Teleport: WebRTC P2P file sharing, won India's largest community hackathon.",
    stack: ["JavaScript", "Python", "WebRTC"],
    proofPoints: [
      "2.5K+ GitHub stars, featured in Awesome-Nodejs/Security lists",
      "Featured in The Hindu and by Facebook",
    ],
    link: "https://github.com/kurolabs/stegcloak",
  },
  "fincorpx": {
    id: "fincorpx",
    device: "laptop",
    title: "FincorpX - Document-AI SaaS Backend",
    period: "Aug – Sep 2024",
    what: "Expense/transaction backend: Azure Form Recognizer + Veryfi OCR, Zoho Books integration, WhatsApp bot, rules engine, plus Python ML transaction classifiers.",
    stack: ["Node.js", "Azure Form Recognizer", "Python / sklearn", "word2vec"],
    proofPoints: [
      "OCR + ML classification in production",
      "Breadth beyond crypto: fintech document automation",
    ],
  },
};
